# Generated by Django 3.2.4 on 2021-06-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('commment', models.TextField(blank=True, null=True)),
                ('source', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('complete_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('birth_date', models.DateTimeField()),
                ('position', models.CharField(max_length=255)),
                ('img_url', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('news_tags', models.ManyToManyField(to='person.News')),
                ('persons_tags', models.ManyToManyField(to='person.Person')),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='persons_news',
            field=models.ManyToManyField(to='person.Person'),
        ),
    ]
