# Generated by Django 3.2.4 on 2021-06-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='persons_news',
            field=models.ManyToManyField(blank=True, to='person.Person'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='news_tags',
            field=models.ManyToManyField(blank=True, to='person.News'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='persons_tags',
            field=models.ManyToManyField(blank=True, to='person.Person'),
        ),
    ]
