# Generated by Django 3.2.4 on 2021-06-05 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_auto_20210605_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='commment',
            new_name='comment',
        ),
    ]
