# Generated by Django 3.2.4 on 2021-06-06 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0009_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
