# Generated by Django 3.2.4 on 2021-06-07 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0010_alter_person_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['id']},
        ),
    ]
